[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://www.digly-solutions.com/*"
  to = "https://digly-solutions.com/:splat"
  status = 301
  force = true
